version: "3"

services:
  server:
    container_name: spk_server
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    volumes:
      - ./server/:/go/src/speaking-exam/server
    ports:
      - 9090:9090
    environment:
      MYSQL_USER: speaking
      MYSQL_PASSWORD: speaking
      MYSQL_HOST: spk_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: speaking
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ap-northeast-1
      AWS_S3_BUCKET: speaking-exam
    depends_on: 
      - db

  db:
    container_name: spk_db
    image: mysql:5.7
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - "./ddl:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: speaking
      MYSQL_PASSWORD: speaking
      MYSQL_DATABASE: speaking
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  proxy:
    container_name: spk_proxy
    build: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - server
