name: Build and Push

on:
  push:
    tags:
      - v*

jobs:
  build-and-push-server-proxy:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build push server image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_SERVER_REPO }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f server/Dockerfile.prod ./server
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Build push proxy image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_PROXY_REPO }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f proxy/Dockerfile.prod ./proxy
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
